#!/usr/bin/env bash
# Prints 'To infinity and beyond' infinity but prints 'I am invincible' when
#+ receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
