#!/usr/bin/env bash
# Configure an Ubuntu server with the below
# `localhost` resolves to `127.0.0.2`
# `facebook.com` resolves to `8.8.8.8`

host_file="/etc/hosts"
tmp_file="$HOME/tmp_hosts"

localhost_dns="localhost"
localhost_ip="127.0.0.2"

facebook_dns="facebook.com"
facebook_ip="8.8.8.8"

if [[ -f $host_file ]]; then
    # modifying a copied version of the file to avoid 'substitution in-place' error
    # then replacing the old hosts file with the modified one
    if ! sudo cp $host_file "$tmp_file"; then
        echo "Exiting process"
        exit 1
    fi

    # replace entire lines that match an ipv4 address and any of our dns with the new ipv4
    sed -i "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\s\+$localhost_dns$/$localhost_ip\t$localhost_dns/g" "$tmp_file"
    sed -i "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\s\+$facebook_dns$/$facebook_ip\t$facebook_dns/g" "$tmp_file"
    sudo cp -f "$tmp_file" $host_file
    rm -f "$tmp_file"
else
    sed -i "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\s\+$localhost_dns$/$localhost_ip\t$localhost_dns/g" "$tmp_file"
    sed -i "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\s\+$facebook_dns$/$facebook_ip\t$facebook_dns/g" "$tmp_file"
    sudo cp -f "$tmp_file" $host_file
    rm -f "$tmp_file"
fi
