#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine it is executed on

# Get all active network interfaces
interfaces=$(ifconfig | grep -Eo '^[^ ]+: ' | cut -d":" -f1)

# Loop through all interfaces and extract the IPv4 address
for interface in $interfaces; do
    ip=$(ifconfig "$interface" | grep -Eo 'inet [0-9.]+' | grep -Eo '[0-9.]+')
    if [ -n "$ip" ]; then
        echo "$ip"
    fi
done
